FROM python:3.9-slim

WORKDIR /app

COPY /loadtest .
RUN apt update
RUN apt install -y build-essential python3-dev libffi-dev libssl-dev
RUN pip install --upgrade pip
RUN pip install locust

CMD ["sh", "-c", "locust -f locust.py --headless --host=$HOST --user 10 --spawn-rate 2 --run-time 10m"]
