primary = {
"naics":  {
    "212":	"Mining other than Oil n Gas",
    "311":	"Food Manufacturing",
    "312":	"Beverage and Tobacco product manufacturing",
    "313":	"Textile mills",
    "314":	"Textile Product mills -- Apparel",
    "315":	"Apparel manufacture",
    "316":	"Leather and alliend product manufacturing",
    "321":	"Wood product manufacturing",
    "322":	"Paper manufacturing",
    "323":	"Printing and related support activities",
    "324":	"Petroleum and coal products manufacture",
    "325":	"Chemical manufacturing",
    "326":	"Plastic and rubber product manufacture",
    "327":	"Nonmetallic mineral product manufacture",
    "331":	"Primary metal manufacturing",
    "332":	"Fabricated metal product manufacture",
    "333":	"Machinery manufacture",
    "334":	"Computer and electronic product manufacture",
    "335":	"Electrical Equipment, appliance, and compoenent manufacture",
    "336":	"Transportation equipment manufacture",
    "337":	"Furniture and related product manufacturing",
    "339":	"Miscelleneous manufacture",
    "4231":	"Motor vehicle and parts merchat wholesalers",
    "4232":	"Furniture and home furnishin merchant wholesalers",
    "4233":	"Lumber and other construction materials merchant wholesalers",
    "4234":	"Commercial equipment merchat wholesalers",
    "4235":	"Metal and mineral (except petrol) merchat wholesalers",
    "4236":	"Electrical and electronic goods merchat wholesalers",
    "4237":	"Hardware and plumbing merchat wholesalers",
    "4238":	"Machinery, equipment, and supplies merchant wholesalers",
    "4239":	"Miscellaneous durable goods merchat wholesalers",
    "4241":	"Paper and paper product merchat wholesalers",
    "4242":	"Drugs and druggists sundries merchat wholesalers",
    "4243":	"Apparel, piece goods, and notions merchant wholesalers",
    "4244":	"Grocery and related product merchat wholesalers",
    "4245":	"Farm product raw material merchat wholesalers",
    "4246":	"Chemical and allied products merchat wholesalers",
    "4247":	"Petroleum and petroleum products merchant wholesalers",
    "4248":	"Beer, wine and distilled alchoholic beverage merchat wholesalers",
    "4249":	"Miscellenous non durrable goods merchat wholesalers",
    "4541":	"Electroning shoppingh and mail-order houses",
    "45431":	"Fuel dealers",
    "4931":	"Warehousing and storage",
    "5111":	"Newspaper, periodical, book, and publisher",
    "551114":	"Corporate, subsidiary, and regional managing office",
},
"export_country": {
"C": "Canada",
"M": "Mexico",
"E": "Europe & Africa",
"A": "Asia & Oceania",
"S": "Rest of the Americas",
"N": "Not an export",
},
"hazmat": {
"P": "Flammable Liquids",
"H": "Hazardous Materials",
"N": "Not HAZMAT"
},
"states": {
    "01":	"Alabama",
    "02":	"Alaska",
    "04":	"Arizona",
    "05":	"Arkansas",
    "06":	"California",
    "08":	"Colorado",
    "09":	"Connecticut",
    "10":	"Delaware",
    "11":	"District of Columbia",
    "12":	"Florida",
    "13":	"Georgia",
    "15":	"Hawaii",
    "16":	"Idaho",
    "17":	"Illinois",
    "18":	"Indiana",
    "19":	"Iowa",
    "20":	"Kansas",
    "21":	"Kentucky",
    "22":	"Louisiana",
    "23":	"Maine",
    "24":	"Maryland",
    "25":	"Massachusetts",
    "26":	"Michigan",
    "27":	"Minnesota",
    "28":	"Mississippi",
    "29":	"Missouri",
    "30":	"Montana",
    "31":	"Nebraska",
    "32":	"Nevada",
    "33":	"New Hampshire",
    "34":	"New Jersey",
    "35":	"New Mexico",
    "36":	"New York",
    "37":	"North Carolina",
    "38":	"North Dakota",
    "39":	"Ohio",
    "40":	"Oklahoma",
    "41":	"Oregon",
    "42":	"Pennsylvania",
    "44":	"Rhode Island",
    "45":	"South Carolina",
    "46":	"South Dakota",
    "47":	"Tennessee",
    "48":	"Texas",
    "49":	"Utah",
    "50":	"Vermont",
    "51":	"Virginia",
    "53":	"Washington",
    "54":	"West Virginia",
    "55":	"Wisconsin",
    "56":	"Wyoming",
},
"mode": {
"2":	"Single mode",
"3":	"Truck",
"4":	"For-hire truck",
"5":	"Company owned truck",
"6":	"Rail",
"7":	"Water",
"8":	"Inland water",
"9":	"Great lakes",
"10":	"Deep sea",
"101":	"Multiple waterways",
"11":	"Air",
"12":	"Pipeline",
"19":	"Other",
"13":	"Multiple mode",
"14":	"Courier",
"20":	"Non-courier",
"15":	"Truck and rail",
"16":	"Truck and water",
"17":	"Rail and water",
"18":	"Other multiple mode",
},
"sctg" : {
    "01":	"Animals and Fish (live)",
    "02":	"Cereal and Grains including seed",
    "03":	"Agricultural products excluding animal feed, cereal grains, and forage products",
    "04":	"Animal feed, eggs, honey, and other products of animal origins",
    "05":	"Meat, poultry, fish, seafood, and their preparation",
    "06":	"Milled grain product and preparation and bakery products",
    "07":	"Other prepared foodstuffs and fats, and oils",
    "08":	"Alcoholic beverages and denatured alcohol",
    "09":	"Tobacco products",
    "10":	"Monumental or building stone",
    "11":	"Natural sands",
    "12":	"Gravel and crushed stone",
    "13":	"Other non metallic minerals not elsewhere classified",
    "14":	"Metallic ores and concentrates",
    "15":	"Coal",
    "16":	"Crude Petroleum",
    "17":	"Gasoline, aviation fuel turbine, and ethanol",
    "18":	"Fuel oil incuded diesel bunker and biodiesel",
    "19":	"Other coal and petroleum products",
    "20":	"Basic chemicals",
    "21":	"Pharmaceutical products",
    "22":	"Fertilizers",
    "23":	"Other chemical products and preparations",
    "24":	"Plastics and rubber",
    "25":	"Logs and other woods in the rough",
    "26":	"Wood products",
    "27":	"Pulp, newspring, paper, and paperboard",
    "28":	"Paper or paperboard articles",
    "29":	"Printed products",
    "30":	"Textiles, leather, and articles of textiles or leather",
    "31":	"Non-metallic mineral products",
    "32":	"Base metal in primary or semi finished forms and finshed basic shapes",
    "33":	"Articles of base metal",
    "34":	"Machinery",
    "35":	"Electronic and other electrical equipment and components and office equipment",
    "36":	"Motorized and other vehicles include parts",
    "37":	"Transportation equipment not elsewhere classified",
    "38":	"Precision instruments and apparatus",
    "39":	"Furniture, mattreses, its supports, lamps, its supports, and signs",
    "40":	"Miscellaneous manufactures products",
    "41":	"Waste and scrap",
    "43":	"Mixed freight",
}
}