#!/usr/bin/env python3
"""Freeze build provenance into ``_buildinfo.py`` before a PyInstaller build.

The frozen binary is the deployed artifact. Without a stamp there is no way to
tell a freshly built binary from one that has been sitting in ``dist/`` since a
previous release -- which is exactly how a stale server binary shipped with a
storage backend it did not understand.

Run immediately before ``pyinstaller``. ``buildinfo`` imports the generated
module when present and falls back to querying git when running from source.
"""
from __future__ import annotations

import datetime
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = ROOT / "_buildinfo.py"
DEFAULT_VERSION = "0.1.0"


def _git(*args: str) -> str:
    try:
        proc = subprocess.run(
            ("git", *args), cwd=ROOT, capture_output=True, text=True,
            timeout=15, check=False,
        )
    except Exception:
        return ""
    return proc.stdout.strip() if proc.returncode == 0 else ""


def _project_version() -> str:
    pyproject = ROOT / "pyproject.toml"
    try:
        match = re.search(r'^version\s*=\s*"([^"]+)"', pyproject.read_text(), re.M)
    except OSError:
        return DEFAULT_VERSION
    return match.group(1) if match else DEFAULT_VERSION


def main() -> int:
    sha = _git("rev-parse", "HEAD") or "unknown"
    if sha != "unknown" and _git("status", "--porcelain"):
        sha += "-dirty"

    version = _project_version()
    build_time = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    TARGET.write_text(
        '"""Generated by tools/stamp_build.py -- do not edit, do not commit."""\n'
        f'VERSION = "{version}"\n'
        f'GIT_SHA = "{sha}"\n'
        f'BUILD_TIME = "{build_time}"\n'
    )
    print(f"stamped {TARGET.name}: version={version} sha={sha} build_time={build_time}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
