name: Build Server Container

on:
  push:
    paths:
      - 'server/server.py'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (optional, required for advanced Docker build)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up Docker login (optional, required if pushing to a registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Run the make command to build the Docker container
      - name: Build Server Container
        run: make create-server-container
