name: Load Test

jobs:
  locust_test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust

    # Step 5: Save Locust report (optional)
    - name: Save Locust report
      env:
        LOCUST_HOST: ${{ secrets.HOST }}
      run: |
        locust -f loadtest/locust.py --headless --host=$LOCUST_HOST --users 10 --spawn-rate 2 --run-time 1m --html=locust_report.html
      continue-on-error: true
    - name: Upload Locust report
      uses: actions/upload-artifact@v3
      with:
        name: locust-report
        path: locust_report.html
