name: Auto Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # pulling container seems take time and eating resources
      # manually adding packages is a good option with
      # compromise in replicability
      # for now we use docker container but we open to other solutions
      image: humamf/dsmlflow:stable
      options: --user root
    steps:
      - name: Set permissions
        run: | 
          sudo chmod -R 777 $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - name: Test all
        run: make test
