name: Auto Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: humamf/dsmlflow:stable
    steps:
      - uses: actions/checkout@v2
      - name: Test all
        working-directory: work
        run: make test
